NAME = snake

CC = cc
CFLAGS = -Wall -Wextra -Werror

SRCS = check_way.c \
		draw_board.c \
		easy_mode.c \
		enable_raw_mode.c \
		generate_obstacles.c \
		hard_mode.c \
		pause_game.c \
		save_score.c \
		snake_main.c \
		snake_starting_coordinates.c \
		spawn_food.c \
		terminalsnake.c \
		wall_check.c

OBJS = $(SRCS:.c=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re